### PR TITLE
Converted 404.html to the new style + prepared master/index.html in Bamboo

### PR DESCRIPTION
**Pull request by ghost**
As well as fixing the very, very lazy copy and pasting mistakes I made.

### CODE REVIEW

**Comment by kestred** [comment]
@Wilee999: While I appreciate the pull request, it isn't adding any particular substantive changes to the documentation.  Pull requests for the documentation should include substantive changes (ie. adding more useful information).  The main reason for this, is because there tends to be a lot of small problems in groups of small changes, and it is causing me to spend extra time writing the documentation.  I also am hesitant to accept documentation that is copied from other repositories (ie. Astron/Astron's docs) because it misrepresents the author/contributor of the documentation, and I will try to avoid accepting further changes of the sort.

As a general note on the plan for what effort should be put in the docs --- Astron and Bamboo will both soon be undergoing large architectural changes which will quickly obsolete a lot of information that could be added to the pages.  As this information would have to be rewritten anyways, I will not be expecting or accepting any documentation that I deem is written on a part of Astron or Bamboo that I believe is likely to change soon.

Additionally, I'd rather not stub out dead pages with just an "in construction".

**Comment by ghost** [comment]
Would it be alright if I resubmitted this with just the 404.html change?

**Comment by kestred** [comment]
While that would be a much more appropriate pull request, I'm also not sure I want to use the exact same documentation page style for error pages on the website.

Additionally, it is really hard to balance humour and professionalism, so the current/new 404 page may need to be rewritten a little anyways (this is part of that additional work problem, with my focus of trying to make Astron a professional but friendly community).

In the end, I would prefer it if an artist took a crack at developing really nice looking error pages, and am inclined to hold off till that happens.  I am particularly fond of GitHub's error pages for example:
- https://github.com/503.html
- https://github.com/404.html
- https://github.com/500.html

**Comment by ghost** [comment]
I'm just that kind of guy who likes to make projects fun :D

**Pull request closed without merging**
